### ISSUE TITLE
example throws error

### ISSUE THREAD

**Issue by ralyodio** [rockets/client#1]
```
$ node comments.js

/Users/username/projects/test/comments.js:15
    contains: [
    ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by rtheunissen** [comment]
Fixed in c3ccff2213245518f9daf79f0512036c26b265df
